# Generated by Django 3.2 on 2021-08-19 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20210611_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_user', to='auth.user'),
        ),
        migrations.CreateModel(
            name='TalkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('talkname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talkname', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
